name: Scala CI

on:
  push:
    branches:
      - '**'  # Все ветки
    pull_request:
      branches:
        - '**'  # Все PR

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3

      - name: Run setup script
        run: |
          chmod +x ./scripts/setup-docker.sh
          ./scripts/setup-docker.sh

      - name: Run tests
        run: sbt test

      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91