name: Scala CI

on:
  push:
    branches:
      - '**'  # Все ветки
    pull_request:
      branches:
        - '**'  # Все PR

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker compose version

      - name: Run setup script
        run: |
          chmod +x ./scripts/setup-docker.sh
          ./scripts/setup-docker.sh

      - name: Run tests
        run: sbt test

  delete-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: build

    steps:
      - name: Delete branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          delete_closed_pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}